### ISSUE TITLE
Provide clearer font requirements

### ISSUE THREAD

**Issue by m0rphed** [igankevich/SaintPetersburg#1]
Please provide list of fonts required to build this theme.

Right now if users don't have distributions of `OpenSans` and `FiraSans Mono` installed then build would fail.

![image](https://user-images.githubusercontent.com/35064145/144450298-232fe60b-7341-4a42-9d75-cd19450ce9d3.png)

Students would likely spend a lot of time figuring out what went wrong if they weren't paying a lot of attention to this errors.

**Comment by igankevich** [comment]
Never saw this error, because I always install all packages from texlive. Is it texlive or some other TeX distribution? Or just ubuntu package manager?
